# Generated by Django 4.0 on 2021-12-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Product', models.CharField(max_length=100)),
                ('Price', models.BigIntegerField()),
                ('Discount', models.IntegerField()),
            ],
        ),
    ]
