# Generated by Django 4.0 on 2021-12-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0002_alter_store_add_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='store_add',
            table=None,
        ),
    ]
