# Generated by Django 3.2.8 on 2022-05-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0003_alter_store_add_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_add',
            name='kg',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store_add',
            name='Discount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
